Core/urls.py
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import include, path

urlpatterns = [
    
    path('traffic-super/', admin.site.urls),
    path('users/', include('Users.urls', namespace='users')),  # Make sure this includes the Users app URLs
    path('dashboard/', include('Dashboard.urls', namespace='dashboard')),  # Dashboard URLs
    path('traffic_spots/', include('Traffic_Spots.urls')),

    # Redirect the root URL to the login page
    path('', lambda request: redirect('users:login')),
    ]

Dashboard/urls.py
from django.urls import path
from . import views

app_name = 'Dashboard'
urlpatterns = [
    path('', views.index, name='index'),  
    path('live_traffic_map/', views.live_traffic_map, name='live_traffic_map'),
    path('traffic_spots_list/', views.traffic_spots_list, name='traffic_spots_list'),
]

Traffic_Spots/urls.py
from django.urls import path
from . import views

app_name = 'Traffic_Spots'

urlpatterns = [
    path('traffic_spots/display/<int:spot_id>/', views.display_traffic_spot, name='display_traffic_spot'),
    path('mark-notification-as-read/<int:notification_id>/', views.mark_notification_as_read, name='mark_notification_as_read'),
]

templates/components/model_objects_counts.html
{% load static %}

{% block content %}

<div class="container-fluid pt-4 px-4">
    <div class="row g-4">
        <div class="col-sm-6 col-xl-3">
            <div class="bg-secondary rounded d-flex align-items-center justify-content-between p-4">
                <i class="fa fa-calculator fa-3x text-primary"></i>
                <div class="ms-3">
                    <p class="mb-2">Spots Found</p>
                    <h6 class="mb-0">{{spots_count}}</h6>
                </div>
            </div>
        </div>
        <div class="col-sm-6 col-xl-3">
            <div class="bg-secondary rounded d-flex align-items-center justify-content-between p-4">
                <i class="fa fa-chart-bar fa-3x text-primary"></i>
                <div class="ms-3">
                    <p class="mb-2">AT Levels</p>
                        <h6 class="mb-0">High</h6>
                </div>
            </div>
        </div>
        <div class="col-sm-6 col-xl-3">
            <div class="bg-secondary rounded d-flex align-items-center justify-content-between p-4">
                <i class="fa fa-chart-area fa-3x text-primary"></i>
                <div class="ms-3">
                    <p class="mb-2">Analysis Aplied</p>
                    <h6 class="mb-0">{{ traffic_analysis_count }}</h6>
                </div>
            </div>
        </div>
        <div class="col-sm-6 col-xl-3">
            <div class="bg-secondary rounded d-flex align-items-center justify-content-between p-4">
                <i class="fa fa-lightbulb fa-3x text-primary"></i>
                <div class="ms-3">
                    <p class="mb-2">Recommendations</p>
                    <h6 class="mb-0">{{ traffic_analysis_count }}</h6>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock%}

templates/components/navbar.html
{% load static %}
<nav class="navbar navbar-expand bg-secondary navbar-dark sticky-top px-4 py-0">
    <a href="#" class="navbar-brand d-flex d-lg-none me-4">
        <h2 class="text-primary mb-0"><i class="fa fa-user-edit"></i></h2>
    </a>
    <a href="#" class="sidebar-toggler flex-shrink-0">
        <i class="fa fa-bars"></i>
    </a>
    <form class="d-none d-md-flex ms-4">
        <input class="form-control bg-dark border-0" type="search" placeholder="Search">
    </form>
    <div class="navbar-nav align-items-center ms-auto">
        <div class="nav-item dropdown">
            <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">
                <i class="fa fa-envelope me-lg-2"></i>
                <span class="d-none d-lg-inline-flex">Message</span>
            </a>
            <div class="dropdown-menu dropdown-menu-end bg-secondary border-0 rounded-0 rounded-bottom m-0">
                <a href="#" class="dropdown-item">
                    <div class="d-flex align-items-center">
                        <img class="rounded-circle" src="{% static 'img/user.jpg'%}" alt=""
                            style="width: 40px; height: 40px;">
                        <div class="ms-2">
                            <h6 class="fw-normal mb-0">Jhon send you a message</h6>
                            <small>15 minutes ago</small>
                        </div>
                    </div>
                </a>
                <hr class="dropdown-divider">
                <a href="#" class="dropdown-item">
                    <div class="d-flex align-items-center">
                        <img class="rounded-circle" src="{% static 'img/user.jpg'%}" alt=""
                            style="width: 40px; height: 40px;">
                        <div class="ms-2">
                            <h6 class="fw-normal mb-0">Jhon send you a message</h6>
                            <small>15 minutes ago</small>
                        </div>
                    </div>
                </a>
                <hr class="dropdown-divider">
                <a href="#" class="dropdown-item">
                    <div class="d-flex align-items-center">
                        <img class="rounded-circle" src="{% static 'img/user.jpg'%}" alt=""
                            style="width: 40px; height: 40px;">
                        <div class="ms-2">
                            <h6 class="fw-normal mb-0">Jhon send you a message</h6>
                            <small>15 minutes ago</small>
                        </div>
                    </div>
                </a>
                <hr class="dropdown-divider">
                <a href="#" class="dropdown-item text-center">See all message</a>
            </div>
        </div>
        <div class="nav-item dropdown">
            <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">
                <i class="fa fa-bell  me-lg-2"></i>
                <span class="d-none d-lg-inline-flex">Notificatin</span>
                {% if notifications %}
                <span class="badge bg-danger me-lg-2">{{ notifications|length }}</span>
                {% endif %}
            </a>
            <div class="dropdown-menu dropdown-menu-end bg-secondary border-0 rounded-0 rounded-bottom m-0">
                {% if notifications %}
                    {% for notification in notifications %}
                        <a href="{% url 'Traffic_Spots:mark_notification_as_read' notification.id %}" class="dropdown-item">
                            <h6 class="fw-normal mb-0">{{ notification.message }}</h6>
                            <small>{{ notification.created_at|timesince }} ago</small>
                        </a>
                        <hr class="dropdown-divider">
                    {% endfor %}
                {% else %}
                    <a href="#" class="dropdown-item text-center">No new notifications</a>
                {% endif %}
                <a href="#" class="dropdown-item text-center">See all notifications</a>
            </div>
        </div>
        <div class="nav-item dropdown">
            <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">
                <img class="rounded-circle me-lg-2" src="{% static 'img/user.jpg'%}" alt=""
                    style="width: 40px; height: 40px;">
                <span class="d-none d-lg-inline-flex">{{ user.first_name }}</span>
            </a>
            <div class="dropdown-menu dropdown-menu-end bg-secondary border-0 rounded-0 rounded-bottom m-0">
                <a href="{% url 'users:login'%}" class="dropdown-item">Log Out</a>
            </div>
        </div>
    </div>
</nav>

templates/components/recent_traffic_spots.html
{% load static %}

{% block content %}

<!-- Recent Sales Start -->
<div class="container-fluid pt-4 px-4">
    <div class="bg-secondary text-center rounded p-4">
        <div class="d-flex align-items-center justify-content-between mb-4">
            <h6 class="mb-0">Recent Traffic Spots</h6>
            <a href="{% url 'Dashboard:traffic_spots_list'%}">Show All</a>
        </div>
        <div class="table-responsive">
            <table class="table text-start align-middle table-bordered table-hover mb-0">
                <thead>
                    <tr class="text-white">
                        <th scope="col"><input class="form-check-input" type="checkbox"></th>
                        <th scope="col">Date</th>
                        <th scope="col">Spot Type</th>
                        <th scope="col">City</th>
                        <th scope="col">Address</th>
                        <th scope="col">Level</th>
                        <th scope="col">Action</th>
                    </tr>
                </thead>
                <tbody>
                    {% for spot in spots  %}
                    <tr>
                        <td><input class="form-check-input" type="checkbox"></td>
                        <!-- <span>{{ spot.created_at|date:"d/m/Y" }}</span> -->
                        <td>{{ spot.created_at|date:"d/m/Y" }}</td>
                        <td>{{ spot.spot_type }}</td>
                        <td>{{ spot.city }}</td>
                        <td>{{ spot.address }}</td>
                        <td>{{ spot.traffic_level }}</td>
                        <td> <a class="btn btn-sm btn-primary" href="{% url 'Traffic_Spots:display_traffic_spot' spot.id %}">Display</a></td>
                    </tr>
                    {% endfor %}
                </tbody>
                
            </table>
        </div>
    </div>
</div>
<!-- Recent Sales End -->

{% endblock%}

templates/components/sidebar.html
{% load static %}
<div class="sidebar pe-4 pb-3">
  <nav class="navbar bg-secondary navbar-dark">
    <!-- Logo start -->
    <a href="{% url 'Dashboard:index'%}" class="navbar-brand mx-4 mb-3">
      <h3 class="text-primary"><i class="fa fa-map me-2"></i>TMMS</h3>
    </a>
    <!-- Logo end -->

    <!-- Username and image start -->
    <div class="d-flex align-items-center ms-4 mb-4">
      <div class="position-relative">
        <img class="rounded-circle" src="{% static 'img/user.jpg'%}" alt="" style="width: 40px; height: 40px;">
        <div class="bg-success rounded-circle border border-2 border-white position-absolute end-0 bottom-0 p-1">
        </div>
      </div>
      <div class="ms-3">
        <h6 class="mb-0">{{ user.first_name }}</h6>
        <span>Admin</span>
      </div>
    </div>
    <!-- Username and image end -->

    <!-- Sidebar start -->
    <div class="navbar-nav w-100">
      <a href="{% url 'Dashboard:index' %}"
        class="nav-item nav-link {% if request.resolver_match.url_name == 'index' %}active{% endif %}">
        <i class="fa fa-cubes me-2"></i>Dashboard
      </a>
      <a href="{% url 'Dashboard:live_traffic_map' %}"
        class="nav-item nav-link {% if request.resolver_match.url_name == 'live_traffic_map' %}active{% endif %}">
        <i class="fa fa-globe me-2"></i>Live Traffic Map
      </a>
      <a href="{% url 'Dashboard:traffic_spots_list' %}"
        class="nav-item nav-link {% if request.resolver_match.url_name == 'traffic_spots_list' %}active{% endif %}"><i
          class="fa fa-map-marker me-2"></i>Traffic Spots</a>
    </div>
    <!-- Sidebar end -->
    <script>
      document.addEventListener('DOMContentLoaded', function () {
        // Get all sidebar links
        const navLinks = document.querySelectorAll('.navbar-nav .nav-link');

        // Loop through each link
        navLinks.forEach(link => {
          link.addEventListener('click', function () {
            // Remove "active" class from all links
            navLinks.forEach(nav => nav.classList.remove('active'));

            // Add "active" class to the clicked link
            this.classList.add('active');
          });
        });
      });

    </script>
  </nav>
</div>

templates/components/traffic_charts.html
{% load static %}

<!-- Sales Chart Start -->

<div class="container-fluid pt-4 px-4">
    <div class="row g-4">
        <div class="col-sm-12 col-xl-6">
            <div class="bg-secondary text-center rounded p-4">
                <div class="d-flex align-items-center justify-content-between mb-4">
                    <h6 class="mb-0">Worldwide Traffic</h6>
                    <a href="">Show All</a>
                </div>
                <canvas id="worldwide-sales"></canvas>
            </div>
        </div>
        <div class="col-sm-12 col-xl-6">
            <div class="bg-secondary text-center rounded p-4">
                <div class="d-flex align-items-center justify-content-between mb-4">
                    <h6 class="mb-0">Local Traffic</h6>
                    <a href="">Show All</a>
                </div>
                <canvas id="salse-revenue"></canvas>
            </div>
        </div>
    </div>
</div>

<!-- Sales Chart End -->

templates/components/widgets.html
{% load static %}
<div class="container-fluid pt-4 px-4">
                <div class="row g-4">
                    <div class="col-sm-12 col-md-6 col-xl-4">
                        <div class="h-100 bg-secondary rounded p-4">
                            <div class="d-flex align-items-center justify-content-between mb-2">
                                <h6 class="mb-0">Messages</h6>
                                <a href="">Show All</a>
                            </div>
                            <div class="d-flex align-items-center border-bottom py-3">
                                <img class="rounded-circle flex-shrink-0" src="{% static 'img/user.jpg'%}" alt=""
                                    style="width: 40px; height: 40px;">
                                <div class="w-100 ms-3">
                                    <div class="d-flex w-100 justify-content-between">
                                        <h6 class="mb-0">Jhon Doe</h6>
                                        <small>15 minutes ago</small>
                                    </div>
                                    <span>Short message goes here...</span>
                                </div>
                            </div>
                            <div class="d-flex align-items-center border-bottom py-3">
                                <img class="rounded-circle flex-shrink-0" src="{% static 'img/user.jpg'%}"alt=""
                                    style="width: 40px; height: 40px;">
                                <div class="w-100 ms-3">
                                    <div class="d-flex w-100 justify-content-between">
                                        <h6 class="mb-0">Jhon Doe</h6>
                                        <small>15 minutes ago</small>
                                    </div>
                                    <span>Short message goes here...</span>
                                </div>
                            </div>
                            <div class="d-flex align-items-center border-bottom py-3">
                                <img class="rounded-circle flex-shrink-0" src="{% static 'img/user.jpg'%}" alt=""
                                    style="width: 40px; height: 40px;">
                                <div class="w-100 ms-3">
                                    <div class="d-flex w-100 justify-content-between">
                                        <h6 class="mb-0">Jhon Doe</h6>
                                        <small>15 minutes ago</small>
                                    </div>
                                    <span>Short message goes here...</span>
                                </div>
                            </div>
                            <div class="d-flex align-items-center pt-3">
                                <img class="rounded-circle flex-shrink-0"src="{% static 'img/user.jpg'%}" alt=""
                                    style="width: 40px; height: 40px;">
                                <div class="w-100 ms-3">
                                    <div class="d-flex w-100 justify-content-between">
                                        <h6 class="mb-0">Jhon Doe</h6>
                                        <small>15 minutes ago</small>
                                    </div>
                                    <span>Short message goes here...</span>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-12 col-md-6 col-xl-4">
                        <div class="h-100 bg-secondary rounded p-4">
                            <div class="d-flex align-items-center justify-content-between mb-4">
                                <h6 class="mb-0">Calender</h6>
                                <a href="">Show All</a>
                            </div>
                            <div id="calender"></div>
                        </div>
                    </div>
                    <div class="col-sm-12 col-md-6 col-xl-4">
                        <div class="h-100 bg-secondary rounded p-4">
                            <div class="d-flex align-items-center justify-content-between mb-4">
                                <h6 class="mb-0">To Do List</h6>
                                <a href="">Show All</a>
                            </div>
                            <div class="d-flex mb-2">
                                <input class="form-control bg-dark border-0" type="text" placeholder="Enter task">
                                <button type="button" class="btn btn-primary ms-2">Add</button>
                            </div>
                            <div class="d-flex align-items-center border-bottom py-2">
                                <input class="form-check-input m-0" type="checkbox">
                                <div class="w-100 ms-3">
                                    <div class="d-flex w-100 align-items-center justify-content-between">
                                        <span>Short task goes here...</span>
                                        <button class="btn btn-sm"><i class="fa fa-times"></i></button>
                                    </div>
                                </div>
                            </div>
                            <div class="d-flex align-items-center border-bottom py-2">
                                <input class="form-check-input m-0" type="checkbox">
                                <div class="w-100 ms-3">
                                    <div class="d-flex w-100 align-items-center justify-content-between">
                                        <span>Short task goes here...</span>
                                        <button class="btn btn-sm"><i class="fa fa-times"></i></button>
                                    </div>
                                </div>
                            </div>
                            <div class="d-flex align-items-center border-bottom py-2">
                                <input class="form-check-input m-0" type="checkbox" checked>
                                <div class="w-100 ms-3">
                                    <div class="d-flex w-100 align-items-center justify-content-between">
                                        <span><del>Short task goes here...</del></span>
                                        <button class="btn btn-sm text-primary"><i class="fa fa-times"></i></button>
                                    </div>
                                </div>
                            </div>
                            <div class="d-flex align-items-center border-bottom py-2">
                                <input class="form-check-input m-0" type="checkbox">
                                <div class="w-100 ms-3">
                                    <div class="d-flex w-100 align-items-center justify-content-between">
                                        <span>Short task goes here...</span>
                                        <button class="btn btn-sm"><i class="fa fa-times"></i></button>
                                    </div>
                                </div>
                            </div>
                            <div class="d-flex align-items-center pt-2">
                                <input class="form-check-input m-0" type="checkbox">
                                <div class="w-100 ms-3">
                                    <div class="d-flex w-100 align-items-center justify-content-between">
                                        <span>Short task goes here...</span>
                                        <button class="btn btn-sm"><i class="fa fa-times"></i></button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>